// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: tamias.proto

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// TamiasClient is the client API for Tamias service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TamiasClient interface {
}

type tamiasClient struct {
	cc grpc.ClientConnInterface
}

func NewTamiasClient(cc grpc.ClientConnInterface) TamiasClient {
	return &tamiasClient{cc}
}

// TamiasServer is the server API for Tamias service.
// All implementations must embed UnimplementedTamiasServer
// for forward compatibility
type TamiasServer interface {
	mustEmbedUnimplementedTamiasServer()
}

// UnimplementedTamiasServer must be embedded to have forward compatible implementations.
type UnimplementedTamiasServer struct {
}

func (UnimplementedTamiasServer) mustEmbedUnimplementedTamiasServer() {}

// UnsafeTamiasServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TamiasServer will
// result in compilation errors.
type UnsafeTamiasServer interface {
	mustEmbedUnimplementedTamiasServer()
}

func RegisterTamiasServer(s grpc.ServiceRegistrar, srv TamiasServer) {
	s.RegisterService(&Tamias_ServiceDesc, srv)
}

// Tamias_ServiceDesc is the grpc.ServiceDesc for Tamias service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tamias_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tamias.Tamias",
	HandlerType: (*TamiasServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "tamias.proto",
}
