// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: tamias.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manufacturer int32

const (
	Manufacturer_MF_UNKNOWN Manufacturer = 0
	Manufacturer_XM         Manufacturer = 1
)

// Enum value maps for Manufacturer.
var (
	Manufacturer_name = map[int32]string{
		0: "MF_UNKNOWN",
		1: "XM",
	}
	Manufacturer_value = map[string]int32{
		"MF_UNKNOWN": 0,
		"XM":         1,
	}
)

func (x Manufacturer) Enum() *Manufacturer {
	p := new(Manufacturer)
	*p = x
	return p
}

func (x Manufacturer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Manufacturer) Descriptor() protoreflect.EnumDescriptor {
	return file_tamias_proto_enumTypes[0].Descriptor()
}

func (Manufacturer) Type() protoreflect.EnumType {
	return &file_tamias_proto_enumTypes[0]
}

func (x Manufacturer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Manufacturer.Descriptor instead.
func (Manufacturer) EnumDescriptor() ([]byte, []int) {
	return file_tamias_proto_rawDescGZIP(), []int{0}
}

type FileType int32

const (
	FileType_FT_UNKNOWN  FileType = 0
	FileType_LARGE_ICON  FileType = 1
	FileType_BIG_PICTURE FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FT_UNKNOWN",
		1: "LARGE_ICON",
		2: "BIG_PICTURE",
	}
	FileType_value = map[string]int32{
		"FT_UNKNOWN":  0,
		"LARGE_ICON":  1,
		"BIG_PICTURE": 2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_tamias_proto_enumTypes[1].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_tamias_proto_enumTypes[1]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_tamias_proto_rawDescGZIP(), []int{1}
}

type UploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manufacturer Manufacturer `protobuf:"varint,1,opt,name=manufacturer,proto3,enum=Tamias.Manufacturer" json:"manufacturer,omitempty"`
	FileType     FileType     `protobuf:"varint,2,opt,name=file_type,json=fileType,proto3,enum=Tamias.FileType" json:"file_type,omitempty"`
	FileUrl      string       `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
}

func (x *UploadReq) Reset() {
	*x = UploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tamias_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReq) ProtoMessage() {}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_tamias_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReq.ProtoReflect.Descriptor instead.
func (*UploadReq) Descriptor() ([]byte, []int) {
	return file_tamias_proto_rawDescGZIP(), []int{0}
}

func (x *UploadReq) GetManufacturer() Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return Manufacturer_MF_UNKNOWN
}

func (x *UploadReq) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FT_UNKNOWN
}

func (x *UploadReq) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type UploadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Ttl int64  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *UploadResp) Reset() {
	*x = UploadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tamias_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResp) ProtoMessage() {}

func (x *UploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_tamias_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResp.ProtoReflect.Descriptor instead.
func (*UploadResp) Descriptor() ([]byte, []int) {
	return file_tamias_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResp) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UploadResp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_tamias_proto protoreflect.FileDescriptor

var file_tamias_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x61, 0x6d, 0x69, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x54, 0x61, 0x6d, 0x69, 0x61, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x54, 0x61, 0x6d,
	0x69, 0x61, 0x73, 0x2e, 0x4d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x2d,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x54, 0x61, 0x6d, 0x69, 0x61, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x30, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x2a, 0x26, 0x0a, 0x0c, 0x4d, 0x61,
	0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x46,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x58, 0x4d,
	0x10, 0x01, 0x2a, 0x3b, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x0a, 0x46, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x4c, 0x41, 0x52, 0x47, 0x45, 0x5f, 0x49, 0x43, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x42, 0x49, 0x47, 0x5f, 0x50, 0x49, 0x43, 0x54, 0x55, 0x52, 0x45, 0x10, 0x02, 0x32,
	0x3b, 0x0a, 0x06, 0x54, 0x61, 0x6d, 0x69, 0x61, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x11, 0x2e, 0x54, 0x61, 0x6d, 0x69, 0x61, 0x73, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x54, 0x61, 0x6d, 0x69, 0x61, 0x73, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tamias_proto_rawDescOnce sync.Once
	file_tamias_proto_rawDescData = file_tamias_proto_rawDesc
)

func file_tamias_proto_rawDescGZIP() []byte {
	file_tamias_proto_rawDescOnce.Do(func() {
		file_tamias_proto_rawDescData = protoimpl.X.CompressGZIP(file_tamias_proto_rawDescData)
	})
	return file_tamias_proto_rawDescData
}

var file_tamias_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tamias_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tamias_proto_goTypes = []interface{}{
	(Manufacturer)(0),  // 0: Tamias.Manufacturer
	(FileType)(0),      // 1: Tamias.FileType
	(*UploadReq)(nil),  // 2: Tamias.UploadReq
	(*UploadResp)(nil), // 3: Tamias.UploadResp
}
var file_tamias_proto_depIdxs = []int32{
	0, // 0: Tamias.UploadReq.manufacturer:type_name -> Tamias.Manufacturer
	1, // 1: Tamias.UploadReq.file_type:type_name -> Tamias.FileType
	2, // 2: Tamias.Tamias.Upload:input_type -> Tamias.UploadReq
	3, // 3: Tamias.Tamias.Upload:output_type -> Tamias.UploadResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tamias_proto_init() }
func file_tamias_proto_init() {
	if File_tamias_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tamias_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tamias_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tamias_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tamias_proto_goTypes,
		DependencyIndexes: file_tamias_proto_depIdxs,
		EnumInfos:         file_tamias_proto_enumTypes,
		MessageInfos:      file_tamias_proto_msgTypes,
	}.Build()
	File_tamias_proto = out.File
	file_tamias_proto_rawDesc = nil
	file_tamias_proto_goTypes = nil
	file_tamias_proto_depIdxs = nil
}
